name: Get Recent Commit Authors
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  get-commits-author:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Recent Commit Authors
        uses: AidarGatin/github-recent-commits-authors@v1.4
        id: recent-commits-authors
        with:
          github_token: ${{ secrets.GH_TOKEN }} # default ''
          days_before: '7' # default 30
          unique: 'true' # default 'true'
          output_format: 'json' # default 'json'

      - name: Print Authors' Emails
        run: |
          echo "Authors' Emails: ${{ steps.recent-commits-authors.outputs.emails }}"
